name: PR Checks

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prettify code
        uses: creyD/prettier_action@v3.1
        with:
          prettier_options: --write **/*.{tsx,js,ts,md,css,scss,html,json,yml}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  eslint:
    name: ESLint
    needs: prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v1

      - name: Install Node.js dependencies
        run: npm install

      - name: Run ESLint
        working-directory: ./src/
        run: npx eslint **/*.{tsx,js,ts} --no-error-on-unmatched-pattern
